name: Automated tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Firefox
        run: sudo apt-get install firefox

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest ./tests