name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: first_tests
        type: choice
        options:
          - first_tests
          - second_tests

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Firefox and Geckodriver
        run: sudo apt-get update
          sudo apt-get install -y firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
          tar xzf geckodriver-v0.34.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: first_tests
        if: "github.event.inputs.deployment_target == 'first_tests'"
        run: pytest ./tests/test_button_page.py -v --alluredir=allure-results

      - name: second_tests
        if: "github.event.inputs.deployment_target == 'second_tests'"
        run: pytest ./tests/test_like_a_button_page.py -v --alluredir=allure-results

      - name: Store allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:

      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'

      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz && sudo tar -zxvf allure-2.23.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure

      - name: Download allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - run: allure generate allure-results -o _site --clean

      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path:
            _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication

    steps:
      - name: Download generated report
        uses: actions/download-artifact@v5
        with:
          name: _site
          path: _site

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3.0.1

      - name: Deploy to github Pages
        uses: actions/deploy-pages@v4.0.5